version: "3"
services:
  sveltekit:
    container_name: sveltekit
    build: ./sveltekit/
    image: node:18-alpine
    restart: unless-stopped
    env_file: ./sveltekit/.env
    ports:
      - "5173:5173"
    networks:
      - strapi
    depends_on:
      - strapi
      
  strapi:
    container_name: strapi
    build: ./strapi-pfapi-app/
    image: strapi:latest
    restart: unless-stopped
    env_file: ./strapi-pfapi-app/.env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: strapiDB
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./strapi-pfapi-app/config:/opt/app/config
      - ./strapi-pfapi-app/src:/opt/app/src
      - ./strapi-pfapi-app/package.json:/opt/package.json
      - ./strapi-pfapi-app/yarn.lock:/opt/yarn.lock
      - ./strapi-pfapi-app/.env:/opt/app/.env
      - ./strapi-pfapi-app/public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi
    depends_on:
      - strapiDB

  strapiDB:
    container_name: strapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: ./strapi-pfapi-app/.env
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/mysql
      #- ./data:/var/lib/mysql # if you want to use a bind folder
    ports:
      - "3306:3306"
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge